### ISSUE TITLE
правки по ДЗ

### ISSUE THREAD

**Issue by kateryna06** [vadikvdk8/vadikvdk8.github.io#1]
1. стили должны лежать в папке со стилями
2. сразу учимся делать css и html красивым и отформатированным, чтоб у нас не было пустых строк
http://joxi.ru/XEA40Gbs3q1xAb  вот как должен выглядеть твой css 
тоже самое касается и html

3.  называем классы правильно.
fidback это не правильное название класса. Есть класс feedback но не fidback

4. для всех ссылок которые ведут на другой сайт нужно прописывать target="_blank"

5. для такой маленькой страницы, ты создал очень много классов. Постарайся удалить хотя бы половину )))

6. Также хотелось бы увидеть что у тебя прописан font для элементов ))

7. background-color: #EEEEEE; лучше использовать сокращенный вариант 
background-color: #EEE; (в css у тебя еще подобное есть) Это не ошибка, но лучше писать сокращенно

Будут вопросы - пиши в скайп

**Comment by kateryna06** [comment]
1. тег <b></b> мы не используем, это устаревшее. Вместо него мы использует тег strong

2. Твое фио лучше сделать не параграфом, а заголовком. 

3. Лучше не усердствовать с использованием id в своей верстке. Они имеют больший вес чем классы, ну и вообще это не очень гуд использовать айдишники для мелких блоков

4. Также хотелось бы увидеть что у тебя прописан font для элементов  - хотелось бы чтоб font был прописан полностью и в сокращенном виде ))

5. Не хватает тенюшки на блоке

**Comment by kateryna06** [comment]
1. font прописан не правильно http://htmlbook.ru/css/font посмотри какой должен быть синтаксис

2. height с main нужно удалить, т.к. если ты решишь добавить еще контент, то он у тебя будет потом обрезаться. По этому, нужно или height заменить на min-height или на последний блок добавить нижний отступ, который не будет давать прилипать контенту к низу

3. посмотри как правильно задаются атрибуты для картинки http://htmlbook.ru/html/img и найди у себя ошибку

4. Нужно убрать все hr. Нужно стараться верстать без лишних тегов и вложенности. И это не семантично. Линию нужно сделать при помощи стилей.

5. сначала пишутся общие стили, а потом уже стили для классов. И все стили должны быть структурированы. Т.е., например, есть блок с классом box, а за ним блок с классом media. Так вот стили для класса box не должны идти после стилей для класса media или быть как-то перемешаны

6. Это хорошо что ты знаешь, что можно задавать не только классы для блоков, но и айдишники ))) Но лучше в своих работах их по возможности избегать. Обычно они задаются на какие-то большие логические блоки или для Js. Вес у id больше чем у class и следовательно перебить стили для id сложнее чем для class. Жить без айдишников можно ))

**Comment by vadikvdk8** [comment]
Катя, шрифты я прописал, если опять не правильно,  то скажи в чем именно проблема. Ссылку по шрифтам, которую ты мне скидывала, я смотрел.
Кажется, все исправил что ты говорила.
Спасибо.

**Comment by kateryna06** [comment]
1. теперь ты font написал правильно. Но теперь нужно все значения для font прописать в 1 строчку )) У вас это было в уроке

2. с элементов которые лежат в блоке line нужно убрать боковые отступы и повесить их на див line. Чтоб если ты решишь добавить другой тег, то он у тебя не прилип к краю.

3. у этих параграфов тоже не должно быть левых отступов http://joxi.ru/LVm6jE3fwKg8mZ У тебя поменяется немного структура

**Comment by vadikvdk8** [comment]
Опять переделал)

**Comment by kateryna06** [comment]
1. повторяющаяся ошибка у тебя есть. ты пишешь, например, margin-bottom: 10 margin-left:5 Но ты же можешь написать margin:0 0 10px 5px Можешь )))) Не нужно плодить несколько строк свойств, если это можно записать все в одну строчку

**Comment by vadikvdk8** [comment]
Опять исправил)
Margin і padding запись одной строкой.

**Comment by kateryna06** [comment]
ЗАЧЕТ

**Comment by vadikvdk8** [comment]
Катя, честно признаюсь, в том что верстку делал по видео Олега. Сам не успеваю разобраться.

**Comment by vadikvdk8** [comment]
У меня в этом проекте куча ошибок), но есть пару вопросов: 
Вопросы по поводу 4 задания:
1.	Как отцентрировать текст и флаг страны между собою в div.countries?
2.	Трьох колоночный + footer макет я правильно сделал? Если нет, то скинь мне, пожалуйста, пример стати в интернете.
3.	Не знаю как сделать высоту .sidebar такой же как и .news.

**Comment by vadikvdk8** [comment]
У меня вопросы:
1.	Как правильно сделать треугольник в меню?
2.	Не могу разобраться как сделать чтоб был контур между выпадающим меню  и основным меню?

**Comment by kateryna06** [comment]
1. можешь повесить картинкой на ссылку, а можно эту стрелочку сделать с помощью css. Есть arrow generator разные, можно поиграться и посмотреть что получится

2. про какой именно контур ты говоришь? не совсем пойму про что ты именно

предыдущие вопросы актуальны или ты разобрался?

**Comment by vadikvdk8** [comment]
Эти вопросы были к lesson3, я не сообразил создать отдельный разговор, а записал все сюда?
Lesson1 ты уже поставила мне «зачет», тогда к нему уже не возвращаемся)
Предыдущие вопросы уже не актуальны, с одними ты мне уже помогла, остальные Олег затрагивал в вебенарах.
Среди всех студентов, которые у тебя есть, я один так туплю )) Скоро уже экзамен, а я только в начале)

**Comment by kateryna06** [comment]
ты не один такой. И вы не тупите, а учитесь, так что все норм ))

**Comment by vadikvdk8** [comment]
Ты меня успокоила))))))
