### ISSUE TITLE
js/lesson 2

### ISSUE THREAD

**Issue by sergolius** [vadikvdk8/vadikvdk8.github.io#10]
1. Нужно сделать реализовать проверку вводимого имени. Не допускать, хотя бы, пустых значений или отмененных.
2. Строки №6-7: Если в строке 6 инициализировать переменную нулем `a = 0` и сменить сравнение `<=` на `<`, то в строке 7 не придется вычитать единицу 
3. Строка №21. Логичней использовать `name` вместо `arr[a]`. Но это больше дело вкуса.

**Comment by vadikvdk8** [comment]
Исправил.

**Comment by sergolius** [comment]
1. Если во время заполнения массива именами нажать Cancel/Отмена, то в строке №7 получим ошибку.
2. Если вводить имена с заглавной буквы (Вадим, Сергей, Татьяна), при заполнении массива и имени для входа в систему, то всегда будем получать алерт с текстом: "Ошибка, такого имени нету".

**Comment by vadikvdk8** [comment]
Переделал.

**Comment by sergolius** [comment]
0. Повальное желание форматировать вводимые имена, приводит к усложнению логики и ошибкам.
1. Проверяй свой код.
Отмена при `'Введите имя для входа в систему:'`, в результате ошибка.
2. Строка 5 `var a;` это избыточный код. Ты делаешь тоже самое в строке 7.
3. `delete input;` это не корректная запись. Потому что нельзя удалить эту переменную. А в нашем случае и не требуется.
3. Выход из цикла:
```javascript
    delete input;
    a = 5;
```
Лучше реализовать как в 30 строке `break;`

**Comment by vadikvdk8** [comment]
Потратил день, так толком и не разобрался, почему, когда я нажимаю в окне “prompt” кнопку “cancel” , то переменные name= «null»(string), а input = null(object). Если есть хорошая статья поводу этой проблемы, пожалуйста, подскажи.
По поводу проверки слов, например: «Саша» и «саша», это разные слова? Я все слова проверял в нижнем регистре.

**Comment by sergolius** [comment]
«Саша» и «саша», да разные строки. Но в задании не указана необходимость проверки на регистры (верхний, нижний).
Например, для авторизации могут использовать логин типа: `tAgiL`.
По поводу `name === 'null'`:
`name` - это глобальная переменная, она предопределена по-умолчанию (`window.name === 'null'`) и эта переменная сохраняется как строка.
Когда пользователь жмет Отмена/Cancel на запрос: `name = prompt('Enter');` происходит присваивание результата глобальной переменной `window.name`: `window.name = 'null';`
Самый простой выход - не использовать глобальные переменные, использовать другие названия. Например использовать переменную с заглавной буквой `Name`.

Протестируй код на ошибки с учетом поправки переменной `name`.
Первая же ошибка при двух Отменах/Cancel подряд.

**Comment by vadikvdk8** [comment]
Спасибо за подсказку. Все исправил.

**Comment by vadikvdk8** [comment]
Спасибо за подсказку. Все исправил.
