### ISSUE TITLE
lesson 3

### ISSUE THREAD

**Issue by kateryna06** [vadikvdk8/vadikvdk8.github.io#2]
1. неправильная ширина на wrapper. Из-за того что ты задал паддинги у тебя увеличилась и ширина

2. шрифт контента у тебя не совпадает с тем что в дизайне. Обычно на body задают шрифт для параграфов. У тебя он не указан ни там ни на параграфах

3. на ссылках в меню тоже нет указаниня названия шрифра

4. http://joxi.ru/jgmvMDVh6go6ra font-size указал, line-height указал а про font-family забыл ((( И эти стили для шрифта лучше прописать на body 

5. http://joxi.ru/4DmBK5RHVoMz2P нужно вынести из Ul И иэто не ссылка

6. следовательно отступы с ul в футере у тебя переместятся на див

7. опять же не указан font-family в футере. Ты чего его так не любишь? )))

8. нет ховера в футее для ссылок.

9. в футере у ссылок активная обасть должна быть только текст http://prntscr.com/8yg7kf вот этой активной области не должно быть

**Comment by vadikvdk8** [comment]
Все исправил. wrapper у меня, кажется,   нормальных размеров (46+968+46)
