### ISSUE TITLE
lesson 3

### ISSUE THREAD

**Issue by kateryna06** [vadikvdk8/vadikvdk8.github.io#3]
1) http://joxi.ru/8ZrJxRjuq9E92j вот этот line-height нужно прописать на body. Я об этом писала в скайпе в чате. Что на body указвается font для всего основного текста, чтоб потом отдельно не дописывать/переписывать стили. Если ты пишешь font, то нужно прописать и line-height. 

2) http://joxi.ru/gV2V0Jvspx6Wrv а где активное состояние у меню?

3) http://joxi.ru/QeAO8x6h0xLYro прилипнут параграфы если добавим еще один. Нужно добавить нижний отступ

4) http://joxi.ru/vDr8zp9hx4wZ26 лишняя обертка. Можно все сделать и без нее. 

5) http://joxi.ru/0KAgRDJf14QX2l во-первый на Ul лишний класс, можно прописать от родителя ей стили, а во-вторых, видишь что блок не подсвечивается, значит что-то пошло не так. Если блоки сделаны правильно, то они подсвечиваются. А не светится он потому, что у него дочерние элементы флоатаются. На ul нужно задать кое-какие свойтсва )) Если не знаешь пиши, скажу

**Comment by kateryna06** [comment]
давай все вопросы по 3 уроку писать сюда, а если есть вопросы по след уроку, то создавай новый  Issue с номером урока, чтоб не запутаться к какому уроку какие вопросы. Ок?

**Comment by vadikvdk8** [comment]
Все исправил! Жду указания на исправление новых ошибок)

**Comment by kateryna06** [comment]
1) http://joxi.ru/752aW9eHL3WOr0 вот этот текст нужно обернуть в див и задать ему класс на который ты повесишь отступы. Но на параграфе нужно будет оставить нижний отступ, чтоб когда добавили еще один, то он не прилип к соседнему

**Comment by vadikvdk8** [comment]
Исправил

**Comment by kateryna06** [comment]
http://joxi.ru/812MynxHpBDq2J этот отстпу нужно повесить просто на параграф, а не от родителя. Чтоб если где-то добавится параграф не в этом блоке он не прилип к следующему

**Comment by kateryna06** [comment]
Так ставлю ЗАЧЕТ. но ты это исправляешь и заливаешь. А то если проверю и не залито, то будет тебе а-на-на!! )))

**Comment by vadikvdk8** [comment]
Исправил)))

**Comment by kateryna06** [comment]
молодец )) ЗАЧЕТ 100%
