### ISSUE TITLE
lesson 4

### ISSUE THREAD

**Issue by vadikvdk8** [vadikvdk8/vadikvdk8.github.io#4]
Исправил.

**Comment by kateryna06** [comment]
1) http://joxi.ru/LVm6jE3fy3PGmZ дают лишнюю активную область

2) текст в логотипе должен быть текстом, а не в картинке

3) http://joxi.ru/L4AkXDEuQjanrq флоат уже дает блочность элементу, так что display лишнее свойство

4) http://joxi.ru/aD2PNkyF7wP7r3 у тебя есть левая и правая часть. Правая часть состоит еще из нескольких блоков. Но это у тебя одно целое. По этому все правые блоки нужно обернуть в один див и его флоатнуть. а дальше выравнивать внутренние блоки. 

5) http://joxi.ru/lbrRqynC0BxaA1 эти свойства тебе тут не нужны. 

6) http://joxi.ru/1bmoyebHROJqAy лучше прописать от меню. И класс лучше перевесить на li

7) http://joxi.ru/lJ2bdoXF3qpyr6 обернуть все в 1 див. У тебя тут левый и правый сайтбар имею одни и теже свойства. Их и назвать надо одинаково. Ты же можешь немного поменять структуру и их флоатнуть все в лево и будет все ок ))

8) http://joxi.ru/lbrRqynC0BXaA1 а где тенюшку и нижний бордер потерял?

**Comment by vadikvdk8** [comment]
Исправил.
Замечание которое ты указала в 5-ом пункте, я сделал так чтоб расстояние между иконками были равные. Так не стоит делать?

**Comment by kateryna06** [comment]
для 5го пункта тебе нужно было убрать ширину и добавить отступы

1) http://joxi.ru/j1A5E0Ju976NAE этот текст не нужно делать отдельный сылкой. Он у тебя должен быть в logo

2) http://joxi.ru/8ZrJxRjualyN2j не нужно тут такой большой отступ

3) http://joxi.ru/L4AkXDEuQnD0rq эту картинку лучше обернуть в див на который ты задашь стили и фиксированную высоту

4) http://joxi.ru/wGrq8DBhpqDBAz неправильно задал z-index. Если появляется такой восклицательный знак значит стили заданы неправильно

**Comment by vadikvdk8** [comment]
Исправил.

**Comment by kateryna06** [comment]
ЗАЧЕТ
