### ISSUE TITLE
Lesson 5

### ISSUE THREAD

**Issue by vadikvdk8** [vadikvdk8/vadikvdk8.github.io#5]
Мой новый сайт!

**Comment by kateryna06** [comment]
1) http://joxi.ru/BLmGOKphy75aml не нужен тут этот класс

2) http://joxi.ru/Ra2XjgYfxqdkrg изначально должны быть ссылки с андерлайном, а при наведении на ссылку андерлайн должен пропадать. Сейчас  у тебя мигающая гирлянда )) с этими андерлайнами. Наводишь на ли андерлайн появляется, а потом наводишь на ссылку и он пропадает

3) http://joxi.ru/jgmvMDVhpkbQra зачем тут clearfix? и не нужно выдумывать классы для активных элементов. Пишешь просто active и все счастливы )))

4) http://joxi.ru/48An1YNcBDGO2O не нужна тут высота

5) http://joxi.ru/Bv29bzyhE8wYAG не тот шрифт. Это не бордер а отдельный блок от формы. И у тебя для заголовка пишутся стили в разным местах

6) http://joxi.ru/0KAgRDJfRQWG2l чекбокс должен быть выровнен по краю

**Comment by vadikvdk8** [comment]
Исправил

**Comment by kateryna06** [comment]
1) http://joxi.ru/82QJ14s1DBQBAd каждый инпут лучше обернуть в див и на него задать нижний отступ. Ну и лейбел соответственно тоже должен быть в диве

**Comment by kateryna06** [comment]
ЗАЧЕТ
