### ISSUE TITLE
js/lessons 3-4

### ISSUE THREAD

**Issue by sergolius** [vadikvdk8/vadikvdk8.github.io#9]
1. Опечатка в css, js: "lable" -> "label".
2. Попробуй все DOM элементы создать не через innerHTML, а с помощью твоего метода `app.createElement`.
3. Для того, что бы кнопка "submit" работала. Нужно обернуть ее и другие элементы формы в тег "form".
4. Объект `param` может содержать не полный набор полей. Например могут отствутствоваться: `tagName`, `inputAtribut`, `className`, `content`, `parent`
По-этому нужно проверять поле перед использованием.
5. Попробуй сделать метод `app.createElement` более универсальным. Что бы можно было установить любое количество атрибутов созданному элементу (перебор свойств объекта: https://learn.javascript.ru/object-for-in).

Если сомневаешься в правильности написания слова на английском, можно использовать гугл переводчик (https://translate.google.com.ua/#en/ru/) или словарь.

**Comment by vadikvdk8** [comment]
Переделал.

**Comment by sergolius** [comment]
Оформил пулл реквест, с мелкими правками.
Зачет.
